"""
Centralised schema definitions. All Bronze columns are StringType.
lca_ prefix replaced with rcm_ throughout.
"""
from pyspark.sql.types import (
    StringType, StructField, StructType, TimestampType,
)

def _str(name): return StructField(name, StringType(), True)
def _ts(name):  return StructField(name, TimestampType(), True)

CHARGES_BRONZE_SCHEMA = StructType([
    _str("rcm_client_id"), _str("rcm_npi"),
    _str("rcm_patient_account_number"), _str("rcm_unique_account_number"),
    _str("org_code"), _str("patient_account_number"), _str("account_suffix"),
    _str("medical_record_number"), _str("charge_id"), _str("empi_number"),
    _str("batch_number"), _str("seq_num"), _str("service_date"),
    _str("charge_posting_date"), _str("amount"), _str("health_plan_type_code"),
    _str("charge_code"), _str("charge_code_type"), _str("revenue_cost_center_code"),
    _str("detail_charge_quantity"), _str("revenue_code"),
    _str("modifier1"), _str("modifier2"), _str("modifier3"),
    _str("charge_code_description"), _str("number_of_units"),
    _str("patient_type_code"), _str("patient_type_code_description"),
    _str("department"), _str("hcpcs_cpt_code"),
    _str("modifier4"), _str("modifier5"), _str("modifier6"),
    _str("type_of_service"), _str("apc_code"), _str("status_indicator"),
    _str("apc_code_date"), _str("discount_formula"), _str("composite_adjustment"),
    _str("hp1_non_covered_amount"), _str("hp1_non_covered_qty"),
    _str("hp2_non_covered_amount"), _str("hp2_non_covered_qty"),
    _str("hp3_non_covered_amount"), _str("hp3_non_covered_qty"),
    _str("exclude_charge_from_calc"), _str("exclude_from_coins_ded_calc"),
    _str("national_drug_code"), _str("corrected_charge_flag"),
    _str("corrected_charge_no"), _str("reposted_charge_no"),
    _str("place_of_service_code"),
    _str("charge_dx_code1"), _str("charge_dx_code2"), _str("charge_dx_code3"),
    _str("charge_dx_code4"), _str("charge_dx_code5"), _str("charge_dx_code6"),
    _str("charge_dx_code7"), _str("charge_dx_code8"), _str("charge_dx_code9"),
    _str("charge_dx_code10"), _str("charge_dx_code_version"),
    _str("charge_dx_code11"), _str("charge_dx_code12"),
    _str("cdm_proration_code"), _str("cdm_prorated_revenue_code"),
    _str("late_charge"), _str("health_plan_number"), _str("client_charge_code"),
    _str("financial_class_at_txn"), _str("service_provider_id"),
    _str("billing_provider_id"), _str("file_date"), _str("host_system"),
    _ts("_ingestion_timestamp"), _str("_source_file"),
])

PATIENTVISITS_BRONZE_SCHEMA = StructType([
    _str("rcm_client_id"), _str("rcm_npi"),
    _str("rcm_patient_account_number"), _str("rcm_unique_account_number"),
    _str("org_code"), _str("patient_account_number"), _str("account_suffix"),
    _str("medical_record_number"), _str("empi_number"), _str("guarantor_number"),
    _str("patient_final_bill_date"), _str("patient_admission_date"),
    _str("patient_discharge_date"), _str("patient_type_code"),
    _str("referring_provider_code"), _str("admitting_provider_code"),
    _str("primary_care_provider_code"), _str("operating_provider_code"),
    _str("attending_provider_code"), _str("financial_class_code"),
    _str("location_code"), _str("total_charges"), _str("current_account_balance"),
    _str("insurance_balance"), _str("total_insurance_payments"),
    _str("total_insurance_adjustments"), _str("patient_balance"),
    _str("total_patient_payments"), _str("total_patient_adjustments"),
    _str("late_charges"), _str("unbilled_charges"), _str("account_status_code"),
    _str("agency_code"), _str("collection_status"), _str("date_placed"),
    _str("next_follow_up_date"), _str("first_mail_date"),
    _str("last_insurance_paid_date"), _str("last_patient_payment_amount"),
    _str("last_patient_payment_date"), _str("outpatient_location"),
    _str("added_date"), _str("outlier_code"), _str("number_of_benefit_days"),
    _str("claim_service_date"), _str("bill_date"), _str("bill_type_code"),
    _str("bill_hold_flag"), _str("original_financial_class_code"),
    _str("bad_debt_collector_code"), _str("accident_type_name"),
    _str("total_payments_from_collection_agency"), _str("type_of_admission"),
    _str("bad_debt_transfer_date"), _str("admit_source_description"),
    _str("registrar_code"), _str("sending_system_name"),
    _str("registration_date"), _str("medicare_remit_date"),
    _str("admission_code"), _str("accident_date"), _str("patient_sub_type_group"),
    _str("discharge_code"), _str("discharge_room"), _str("discharge_bed"),
    _str("length_of_stay"), _str("total_adjustments"), _str("unit_vip_level_code"),
    _str("ur_charge_total"), _str("ar_charge_total"), _str("method_of_arrival"),
    _str("discharge_nursing_station_code"), _str("discharge_nursing_station_name"),
    _str("transfer_to_facility"), _str("pre_authorization_flag"),
    _str("coder_identifier"), _str("code_date"),
    _str("total_time_worked_on_account"), _str("zero_balance_date"),
    _str("last_worked_date"), _str("total_allowances"), _str("total_write_offs"),
    _str("credit_balance_date"), _str("service_code"), _str("scheduled_service"),
    _str("type_of_service"), _str("total_payments"), _str("authorized_days"),
    _str("admit_source_code"), _str("ub04_admit_type"), _str("calc_today_flag"),
    _str("archive_ind"), _str("stop_contractual_allowance_extract_ind"),
    _str("ipf_per_diem_begin_day"), _str("eval_date"), _str("referral_date"),
    _str("invoice_number"), _str("corrected_charge_flag"),
    _str("corrected_charge_no"), _str("reposted_charge_no"), _str("charge_id"),
    _str("total_refunds"), _str("irf_value"), _str("case_mix_group_value"),
    _str("patient_responsibility"), _str("vip_code_description"),
    _str("active_payer_indicator"), _str("account_assign_date"),
    _str("provider_code"), _str("bad_debt_flag_yn"), _str("pre_admission_flag"),
    _str("mothers_account_number"), _str("test_patient"),
    _str("current_health_plan_number"), _str("appointment_made_date"),
    _str("expected_reimbursement_amount"), _str("file_date"), _str("host_system"),
    _ts("_ingestion_timestamp"), _str("_source_file"),
])
